# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Kyra Flesvig
description: "Hi! I'm Kyra, a Marketing and Sport Management professional passionate about building ideas that create real impact. This portfolio showcases projects that blend strategy, storytelling, and results. Connect with me on LinkedIn, explore my GitHub, or download my resume below."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: subtitle:<span style='color:#1abc9c'> Sports Marketing Portfolio </span>
location: "Valparaiso, IN"
resume_url: /docs/KyraFlesvigResume.pdf
avatar_image: /img/kyraflesvigheadshot.png

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/kyra-flesvig-977687290/" # Add your linkedln handle
github: "https://kyraflesvig04.github.io"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false
      
#-------------------------------
# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
    


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

















